inputfolder="Y:/perrimon/Opera/plates/RalphNeumuller/103B116/";
outputfolder="Y:/perrimon/Opera/uncompressed_plates/103B116/";

recursiveglob(inputfolder & "*.flex"|files)

foreach(files, "file") {
     readflex(file|sourcedata, sourcedataprop, tifftags)
     sourcedata.compressiontype[:] = "";
     pathsplit(file|basename)
     writeflex(outputfolder & basename, sourcedata=sourcedata, sourcedataprop=sourcedataprop, tifftags=tifftags)
}